version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '5412:5412'
    depends_on:
      - postgresdb
      - redisCache
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network
    env_file:
      - .env

  postgresdb:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=post123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=alhayat

    networks:
      - node-network

  redisCache:
    image: "redis:alpine"
    ports:
      - 6379:6379
    networks:
      - node-network

volumes:
  dbdata:
    driver: local

networks:
  node-network:
    driver: bridge
